### PR TITLE
Initial commit to GitHub repo with Azure DevOps pipelines

### PR DESCRIPTION
**Pull request by bugraderre**

### CODE REVIEW

**Comment by bugraderre** [comment]
@mkaszub 
Concerning the main module name:
* cdock
* cdcore
* ... others?

**Comment by bugraderre** [comment]
While striving GitHub for Python projects it seems that the main modules reflect the package name. One good example was the Science Kit Learn package. The Python main module was named *sklearn* then. Besides the Science Kit nearly every Python project did it that way.

In our case *cdcore* would not fit. The chaos-dock is the chaos-dock but not the chaos-dock-core. What about renaming our package that is going to be deployed?

Something like:
* chaos-dock-kit (-> cdkit in main module)
* chaos-dock-core (-> cdcore in main module)
* chaos-dock-cli (-> cdcli)
...

**Comment by mkaszub** [comment]
The naming you propose LGTM. How do we want to call the module that user has to install? *-core or *-kit? 

For me "kit" sounds more appealing but currently we have rather "controller" that is closer to the -core... :)

**Comment by bugraderre** [comment]
You surely mean the package that the user is going to install.

Let's call it chaos-dock-kit and main module inside cdkit.

I know that it offers more controllers than being a kit really :) Anyway it offers some "kit" features - you can crawl experiments and run them :) And there is maybe more to come later.

Agree?

**Comment by bugraderre** [comment]
@mkaszub After all our naming cycles I warmly invite you to have a look at this PR and feel free to merge.

**Pull request merged**
